###  Crear un nuevo recurso
POST http://localhost:3000/api/recursos
Content-Type: application/json

{
  "nombre": "Teclado Mecánico",
  "precio": 150
}

###  Crear otro recurso
POST http://localhost:3000/api/recursos
Content-Type: application/json

{
  "nombre": "Mouse Inalámbrico",
  "precio": 80
}

### Obtener todos los recursos
GET http://localhost:3000/api/recursos

### Obtener recursos con límite (Query Param)
GET http://localhost:3000/api/recursos?limite=1

### Modificar un recurso por ID
PUT http://localhost:3000/api/recursos/1
Content-Type: application/json

{
  "nombre": "Teclado RGB Pro",
  "precio": 180
}

### Eliminar un recurso por ID
DELETE http://localhost:3000/api/recursos/2

### Validación: Error al enviar un precio negativo (400 Bad Request)
POST http://localhost:3000/api/recursos
Content-Type: application/json

{
  "nombre": "Monitor",
  "precio": -100
}

### Validación: Error al buscar ID inexistente (404 Not Found)
PUT http://localhost:3000/api/recursos/999
Content-Type: application/json

{
  "nombre": "No existe",
  "precio": 50
}